import 'package:hive_flutter/hive_flutter.dart';
import 'package:pengespareapp/src/features/products/domain/models/product.dart';
import 'package:pengespareapp/src/features/products/domain/models/product_category.dart';
import 'package:pengespareapp/src/features/settings/data/app_settings.dart';
import 'package:pengespareapp/src/features/achievements/data/achievement.dart';

class DatabaseService {
  static const String settingsBoxName = 'settings';
  static const String productsBoxName = 'products';

  // Initialize Hive and register adapters
  static Future<void> init() async {
    await Hive.initFlutter();

    // Register type adapters (generated by build_runner)
    Hive.registerAdapter(ProductAdapter());
    Hive.registerAdapter(ProductStatusAdapter());
    Hive.registerAdapter(PurchaseDecisionAdapter());
    Hive.registerAdapter(AppSettingsAdapter());
    Hive.registerAdapter(ProductCategoryAdapter());
    Hive.registerAdapter(AchievementAdapter());

    // Open boxes
    await Hive.openBox<AppSettings>(settingsBoxName);
    await Hive.openBox<Product>(productsBoxName);
  }

  // Get settings box
  static Box<AppSettings> getSettingsBox() {
    return Hive.box<AppSettings>(settingsBoxName);
  }

  // Get products box
  static Box<Product> getProductsBox() {
    return Hive.box<Product>(productsBoxName);
  }

  // Get or create default settings
  static AppSettings getSettings() {
    final box = getSettingsBox();
    if (box.isEmpty) {
      final defaultSettings = AppSettings();
      box.put('settings', defaultSettings);
      return defaultSettings;
    }
    return box.get('settings')!;
  }

  // Update settings
  static Future<void> updateSettings(AppSettings settings) async {
    final box = getSettingsBox();
    await box.put('settings', settings);
    // Also call save() since AppSettings extends HiveObject
    await settings.save();
  }

  // Get all active products (waiting or completed status)
  static List<Product> getActiveProducts() {
    final box = getProductsBox();
    return box.values
        .where((p) => p.status != ProductStatus.archived)
        .toList()
      ..sort((a, b) => b.createdAt.compareTo(a.createdAt));
  }

  // Get archived products
  static List<Product> getArchivedProducts() {
    final box = getProductsBox();
    return box.values
        .where((p) => p.status == ProductStatus.archived)
        .toList()
      ..sort((a, b) => b.createdAt.compareTo(a.createdAt));
  }

  // Add product
  static Future<void> addProduct(Product product) async {
    final box = getProductsBox();
    await box.put(product.id, product);
  }

  // Update product
  static Future<void> updateProduct(Product product) async {
    await product.save();
  }

  // Delete product
  static Future<void> deleteProduct(String id) async {
    final box = getProductsBox();
    await box.delete(id);
  }

  // Calculate statistics
  static Map<String, dynamic> calculateStats() {
    final box = getProductsBox();
    final products = box.values.toList();

    double moneySaved = 0;
    int impulseBuys = 0;
    int plannedPurchases = 0;
    int avoided = 0;

    for (final product in products) {
      if (product.decision == PurchaseDecision.avoided) {
        moneySaved += product.price;
        avoided++;
      } else if (product.decision == PurchaseDecision.impulseBuy) {
        impulseBuys++;
      } else if (product.decision == PurchaseDecision.plannedPurchase) {
        plannedPurchases++;
      }
    }

    final totalDecisions = avoided + impulseBuys + plannedPurchases;
    final impulseControlScore = totalDecisions > 0 
        ? ((avoided + plannedPurchases) / totalDecisions * 100).toInt()
        : 100;

    final settings = getSettings();
    final hoursSaved = settings.hourlyWage > 0 
        ? moneySaved / settings.hourlyWage 
        : 0.0;

    return {
      'moneySaved': moneySaved,
      'hoursSaved': hoursSaved,
      'impulseControlScore': impulseControlScore,
      'impulseBuys': impulseBuys,
      'plannedPurchases': plannedPurchases,
      'avoided': avoided,
    };
  }
}
